apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    customer: amos
spec:
  selector:
    matchLabels:
      app: web
  replicas: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: amosshahar/simpleweb:1.0
        name: web-container
        ports:
        - containerPort: 8080